# Generated by Django 5.2.4 on 2025-07-15 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MilkProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('producer_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MilkCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('milk_type', models.CharField(choices=[('buffalo', 'Buffalo'), ('cow', 'Cow')], max_length=10)),
                ('morning_litres', models.FloatField(default=0)),
                ('evening_litres', models.FloatField(default=0)),
                ('fat_value', models.FloatField()),
                ('snf', models.FloatField()),
                ('rate', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.milkproducer')),
            ],
        ),
        migrations.CreateModel(
            name='MilkRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_type', models.CharField(choices=[('buffalo', 'Buffalo'), ('cow', 'Cow')], max_length=10)),
                ('fat_value', models.FloatField()),
                ('rate', models.FloatField()),
            ],
            options={
                'unique_together': {('milk_type', 'fat_value')},
            },
        ),
    ]
