# Generated by Django 5.2.4 on 2025-07-16 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('advance_money', models.FloatField(default=0)),
                ('feed_money', models.FloatField(default=0)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.milkproducer')),
            ],
        ),
    ]
