# Generated by Django 5.2.4 on 2025-08-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerdeduction',
            name='adjustment_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='producerdeduction',
            name='payment_adjustment',
            field=models.FloatField(default=0),
        ),
    ]
