# Generated by Django 5.2.4 on 2025-07-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producerdeduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerdeduction',
            name='advance_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='producerdeduction',
            name='feed_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='producerdeduction',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
