# Generated by Django 5.2.4 on 2025-08-11 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250811_1220'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='milkrate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='milkproducer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milkrate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='milkproducer',
            name='producer_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='milkrate',
            unique_together={('user', 'milk_type', 'fat_value')},
        ),
    ]
